### ISSUE TITLE
Documentation for S3 uploads

### ISSUE THREAD

**Issue by jbouse** [nibogd/ingress-ice#83] opened 2016-02-23 04:46 UTC
I'm trying to get ICE to upload my screenshots to S3 but it doesn't seem to be working. Do you have any example documentation on the configuration options to make sure I've got it set right in there?

I've created an IAM user with it's own Access Key and Secret Key Id... I've granted it AmazonS3FullAccess policy rights.

I see ICE is taking the screenshots okay as I thankfully didn't set S3Remove to true. The console shows the log entry stating it's uploading to S3 but the images do not appear in the bucket.

**Comment by nibogd** [comment] 2016-02-23 21:37
Hmm… Sorry, I don't have an Amazon account and i cant test that. The uploader code was contributed by @c2nprds (#35), maybe he knows?..

**Comment by jbouse** [comment] 2016-02-23 22:53
Yeah I tried to find the commit that brought it in but seems like when you split the ice.js into multiple files the history got lost and I couldn't find the PR for it.

**Comment by nibogd** [comment] 2016-02-23 23:05
Yep, ice became too big to keep everything in a single file :sweat:

**Comment by kelt8** [comment] 2016-02-24 02:34
Confirmed, not working for me either. No errors shown.

**Comment by timmpw** [comment] 2016-03-23 09:28
Confirmed, not working for me too.
23.03.2016 12:24:33: The first screenshot may not contain all portals, it is intended for you to check framing.
23.03.2016 12:24:35: Screen saved
23.03.2016 12:24:35: Uploading to Amazon S3...

**Comment by c2nprds** [comment] 2016-04-19 06:46
@nibogd 
oops sorry. Was not look issue.

https://github.com/nibogd/ingress-ice/blob/master/ice/modules/ice-60-core.js#L151
Argument `file` == `filename` ?? require `file path` !

Look at the
https://github.com/nibogd/ingress-ice/blob/master/ice/modules/ice-20-aws.js#L20

**Comment by nibogd** [comment] 2016-04-19 08:45
Thank you, @c2nprds ! Fixed in #87

**Closed by nibogd** 2016-04-19 08:45 UTC
